version: '3.8'

services:
  student-service:
    image: elumalai25/tamilschool:latest
    ports:
      - "8081:8080"
    depends_on:
      - discovery-service
      - postgres
      - course-service
    environment:
      SPRING_PROFILES_ACTIVE: pq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
      SPRING_DATASOURCE_USERNAME: sikar
      SPRING_DATASOURCE_PASSWORD: pass@123
    networks:
      - student-network

  course-service:
    image: elumalai25/course-service:latest
    ports:
      - "8082:8080"
    depends_on:
      - discovery-service
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: pq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student
      SPRING_DATASOURCE_USERNAME: sikar
      SPRING_DATASOURCE_PASSWORD: pass@123
    networks:
      - student-network

  discovery-service:
    image: elumalai25/discovery-service:latest
    ports:
      - "8761:8761"
    networks:
      - student-network

  postgres:
    image: postgres:13
    container_name: studentPostgres
    environment:
      POSTGRES_USER: sikar
      POSTGRES_PASSWORD: pass@123
      POSTGRES_DB: student
    ports:
      - "5432:5432"
    networks:
      - student-network

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    environment:
      - JENKINS_OPTS="--httpPort=8080"  # Change this to your desired port
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - student-network

volumes:
  jenkins_home:
    driver: local

networks:
  student-network:
    driver: bridge
