server:
    address: 0.0.0.0
    port: 8080
spring:
    application:
        name: tamilSchool
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
