spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
#        url: jdbc:h2:mem:testdb
        username: elumalairamalingam
        password: sikar
        ddl-auto: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
